### ISSUE TITLE
Test dependencies: `jo`, a local MQTT server

### ISSUE THREAD

**Issue by vielmetti** [jpmens/msoak#11]
Two minor dependencies that would be worth noting, not to build the system, but to test it according to directions:

1. The test example code in the README uses `jo` to generate JSON. Of course you should have it installed already! But if you don't yet, that would be good to explicitly document where to get it from.

2. The example config connects to an MQTT server on `localhost`, but if for some reason you don't have one running, it errors with `msoak: Disconnected from loc. Reason: 0x0E [MOSQ_ERR_ERRNO] Broken pipe`. Fortunately the error is not fatal (cf #2) and it successfully connects to the other servers, which in my limited test experience do generally have test traffic that are sufficient to convince me that something is working.

**Comment by jpmens** [comment]
I agree with 1. and will document it with a link.

Number 2 is a bit harder. Actually I’m not at all a fan of by default pointing to foreign servers, but I see no other way of doing it. I was hoping that people who look at `msoak` would have their own broker. 

The reason I don’t like pointing at _TMO_ for instance is that I cannot predict whether it’ll be operational, or worse, what horrid octet sequences will be printed to the _msoak_ tester’s terminal!

I’m open to suggestions.

**Comment by vielmetti** [comment]
A horrible solution is to run your own broker, which exists solely to emit test traffic, and which doesn't accept any 3d party incoming traffic. Every minute it spits out "At the tone the time will be", temperatures on the 10 second mark, atmospheric readings at 20 seconds, etc. An advanced channel would iterate through error conditions. 

A possibly helpful test setup is to reference the MQTT list of public test servers, e.g. at https://github.com/mqtt/mqtt.github.io/wiki/public_brokers

The simplest thing that could possibly work is a line to the effect of this in the README:

To test msoak, you will need a source of MQTT test traffic, This could be a test server or a production server that you run, or one of the public test servers (link). The example configuration assumes that you have a test server running on `localhost`; edit this to suit.

**Comment by jpmens** [comment]
We won't do our own broker, in spite of how much I'd like to.

I'm copying the sentence you propose into the README. Thank you; it's perfect.
