### ISSUE TITLE
Alpine Linux: dependency check

### ISSUE THREAD

**Issue by vielmetti** [jpmens/msoak#12]
Not quite enough time to finish this now, but some notes. Alpine might be a nice choice if this thing lands in a container at some point, so this is in preparation that that.

- You'll need to edit the Makefile, of course, at least until #9 is resolved.
- Libraries needed include `libbsd`, `mosquitto-libs` , and some version of Lua.
- The default Lua looks like 5.1, I think there's a 5.3 available, still checking.
- the package manager is `apk`.

Alpine notably has a different libc (`musl`) so there's some chance of portability issues there, worth checking.

**Comment by jpmens** [comment]
Do me a favor please? What does our minature `Makefile` say about Alpine? I hope not "linux" ... :)

**Comment by vielmetti** [comment]
Yes, our mini Makefile returns `linux` when it's running in a container under Ubuntu. I'll report back when I get a chance to run it native

One snag, `pkg-config` is replaced by `pkgconf`, see https://github.com/pkgconf/pkgconf/wiki/Roadmap for that. I get this error at build time:

```
Package lua5.3 was not found in the pkg-config search path.
Perhaps you should add the directory containing `lua5.3.pc'
to the PKG_CONFIG_PATH environment variable
```

I'm sure there is a whole long story about the differences between `pkg-config` and `pkgconf`, but I haven't found them yet.

**Comment by vielmetti** [comment]
pkgconf is a Fedora thing, see https://fedoraproject.org/wiki/Changes/pkgconf_as_system_pkg-config_implementation

**Comment by vielmetti** [comment]
The Lua5.3 config for Alpine looks like it's sorted out at https://github.com/vim/vim/issues/4475 (where `configure` gets it wrong). And I'm not finding any `lua5.3.pc` file in my Alpine after I install it, so it'll be probably best to hard-code the path rather than discover it.

**Comment by vielmetti** [comment]
Something, somewhere along the way, is using <sys/cdefs.h> and Alpine is not happy about it. (I think it's the BSD package.)

https://github.com/alpinelinux/aports/commit/a109caf76a9432a80ba408a5250aa454fc8bee0c

As a consequence, you can't build with -Werror.

A fragment of my Makefile - still not 100% sure about dependencies, because some of what I want is in meta-packages, but here we go:

```
### Alpine LInux
CFLAGS = -I/usr/include/lua5.3 -Wall -I.
LDFLAGS += -L/usr/lib/lua5.3 -llua -lbsd
BINDIR = /usr/local/bin
MANDIR = /usr/local/share/man
```

**Comment by vielmetti** [comment]
With these dependencies, the system builds:

`apk add build-base libconfig-dev mosquitto-dev lua5.3-dev libbsd-dev`

And the thing you get runs as you'd expect.

However, you get this ugly error message at build time:

```
In file included from /usr/include/bsd/sys/cdefs.h:51,
                 from /usr/include/bsd/string.h:39,
                 from msoak.c:23:
/usr/include/sys/cdefs.h:1:2: warning: #warning usage of non-standard #include <sys/cdefs.h> is deprecated [-Wcpp]
    1 | #warning usage of non-standard #include <sys/cdefs.h> is deprecated
      |  ^~~~~~~
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../lib/libc.so: warning: This
function cannot be safely ported, use getline(3) instead, as it is supported by GNU and POSIX.1-2008.
```

**Comment by vielmetti** [comment]
OK, more portability fun.

the `musl` C library includes `strlcpy`, which is one of the reasons that -libbsd is included on Linux systems.

The `glibc` controvery regarind `strlcpy` seems to go back as far as the year 2000, per https://lwn.net/Articles/507319/ and https://lwn.net/Articles/612244/

On Alpine, I can wipe out all the ugly error messages with this patch:

```
diff --git a/msoak.c b/msoak.c
index 47b92aa..8ecad16 100644
--- a/msoak.c
+++ b/msoak.c
@@ -19,7 +19,7 @@
 #include <stdio.h>
 #include <stdlib.h>
 #include <stdbool.h>
-#ifdef __linux__
+#if defined(__linux__) && defined(__GLIBC__)
 #include <bsd/string.h>
 #endif
 #include <string.h>
```

and dropping the `libbsd-dev` include.

**Comment by jpmens** [comment]
Goodness me, thankfully I was sleeping the sleep of the innocent whilst you went digging into the past for `strlcpy`...

I will now apply your wisdom, er, code to _msoak_ with many thanks.
