### ISSUE TITLE
Ubuntu: builds fail with MOSQ_ERR_LOOKUP undefined

### ISSUE THREAD

**Issue by vielmetti** [jpmens/msoak#8]
Tried on two Ubuntu systems: WSL 1 running under Windows 10 on Arm, and Ubuntu 16.04 running on Packet's t1.small.x86.

The error is 

```
msoak.c: In function ‘mosquitto_reason’:
msoak.c:73:28: error: ‘MOSQ_ERR_LOOKUP’ undeclared (first use in this function)
```

libmosquitto-dev on the Ubuntu 16.04 machine:

```
libmosquitto-dev/xenial-updates,xenial-security,now 1.4.8-1ubuntu0.16.04.7 amd64 [installed]
```

libmosquitto-dev on the WSL (Ubuntu 18) machine:

```
libmosquitto-dev/bionic-updates,bionic-security,now 1.4.15-2ubuntu0.18.04.3 arm64 [installed]
```

**Comment by vielmetti** [comment]
Looks like MOSQ_ERR_LOOKUP was added with this issue https://github.com/eclipse/mosquitto/issues/850

**Comment by vielmetti** [comment]
libmosquitto has a PPA for Ubuntu. I was able to install per the instructions at 

https://www.eclipse.org/mosquitto/download/#linux

```
sudo apt-add-repository ppa:mosquitto-dev/mosquitto-ppa
```

This pulled the version forward to 

```
Setting up libmosquitto1:amd64 (1.6.8-0mosquitto1~xenial1)
```

And with that, those MOSQ_ERR_LOOKUP problems go away. Alas, the supplied PPA does not have `arm64` bits.

**Comment by jpmens** [comment]
I’ve committed a fix which will hopefully solve the issue.

**Comment by vielmetti** [comment]
That took care of it - the Ubuntu 16 machine with the upgraded libmosquitto worked fine, and the WSL 1 machine with the old libmosquitto worked fine too!
